server {
    listen 8081;
    server_name 124.223.78.223;

    root /opt/work-file-archive/frontend/dist;
    index index.html;
    client_max_body_size 2048m;

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8010/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
    }

    location /docs {
        proxy_pass http://127.0.0.1:8010/docs;
        proxy_set_header Host $host;
    }

    location /openapi.json {
        proxy_pass http://127.0.0.1:8010/openapi.json;
        proxy_set_header Host $host;
    }
}
